### ISSUE TITLE
w3m config

### ISSUE THREAD

**Issue by Jab2870** [gotbletu/dotfiles#3]
Hi, your w3m config in w3m/.w3m doesn't appear to be the same as the config I have seen in some of your videos. Am I missing something / looking in the wrong place.

I am particularly interested in what looks like your fzf integration from this video:

https://open.lbry.com/@gotbletu:b/gotbletu-terminal-web-browsing-workflow:a

**Comment by gotbletu** [comment]
oh yea, few people have ask about it, i havent made a video on it yet sorry. i will try to explain it in my next few videos

**Comment by gotbletu** [comment]
ok uploaded, https://lbry.tv/@gotbletu:b/w3m-prefix-search-engine-searches-via:9

**Comment by Jab2870** [comment]
Thanks very much! very helpful. Could you also share your scripts for toggling images / table borders at run time?

**Comment by gotbletu** [comment]
yes, for sure, ill have to remember how i did it 1st lols, is been a while, but ill post up a video once i do
